### PR TITLE
Added some killer humour

### PR DESCRIPTION
**Pull request by steerjon**
Last pull request preceded a necessary commit

### CODE REVIEW

**Comment by steerjon** [comment]
All run through no problems - will go to master and see how we're doing

**Comment by steerjon** [comment]
Option to delete branch but keeping coz think pull request was a mistake

**Comment by tomgillsteer** [comment]
I think it looks good actually
i'll merge in mine next

**Comment by tomgillsteer** [comment]
Deleting branches when they are done with it cleans stuff up You can always undelete a branch - nothing is ever lost in Git (muhahah)

**Comment by steerjon** [comment]
Deleted ...

**Pull request merged**
